spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyan_db?useSSL=false&characterEncoding=utf-8
    username: root
  profiles:
    active: xrw
server:
  port: 8083
  servlet:
    context-path: /