spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyan_market?useSSL=false&characterEncoding=utf-8
    username: root
pagehelper:
  helper-dialect: mysql